/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "SWGModel.h"

#include "SWGCurrency.h"

#include "SWGObject.h"

namespace Swagger 
{


/*
 * SWGAmount.h
 *
 * some description 
 */
class SWG_API SWGAmountRequest: public Request
{
public:
    virtual ~SWGAmount() {}
    bool IsValid() const override;
	TSharedPtr<FJsonObject> ToJson() const override;
    
    double value = 0.0;
    SWGCurrency* currency = new SWGCurrency();
};

class SWG_API SWGAmountResponse: public Response
{
public:
    virtual ~SWGAmount() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	bool ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject) override;

	class SWGAmountErrorDetails : public ErrorDetails
	{
	public:
		virtual ~SWGAmountErrorDetails() {}
		bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	};
	const SWGAmountErrorDetails& GetError() const { check(_Error); return *_Error.Get(); }
    
    //TODO: error vars here
    double value;
    SWGCurrency* currency;

private:
	TUniquePtr<SWGAmountErrorDetails> _Error;
};


}
