/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "SWGModel.h"


#include "SWGObject.h"

namespace Swagger 
{


/*
 * SWGApiResponse.h
 *
 * Describes the result of uploading an image resource
 */
class SWG_API SWGApiResponseRequest: public Request
{
public:
    virtual ~SWGApiResponse() {}
    bool IsValid() const override;
	TSharedPtr<FJsonObject> ToJson() const override;
    
    int32 code = 0;
    FString type = new FString("");
    FString message = new FString("");
};

class SWG_API SWGApiResponseResponse: public Response
{
public:
    virtual ~SWGApiResponse() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	bool ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject) override;

	class SWGApiResponseErrorDetails : public ErrorDetails
	{
	public:
		virtual ~SWGApiResponseErrorDetails() {}
		bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	};
	const SWGApiResponseErrorDetails& GetError() const { check(_Error); return *_Error.Get(); }
    
    //TODO: error vars here
    int32 code;
    FString type;
    FString message;

private:
	TUniquePtr<SWGApiResponseErrorDetails> _Error;
};


}
