/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "SWGModel.h"


#include "SWGObject.h"

namespace Swagger 
{


/*
 * SWGCurrency.h
 *
 * some description 
 */
class SWG_API SWGCurrencyRequest: public Request
{
public:
    virtual ~SWGCurrency() {}
    bool IsValid() const override;
	TSharedPtr<FJsonObject> ToJson() const override;
    
};

class SWG_API SWGCurrencyResponse: public Response
{
public:
    virtual ~SWGCurrency() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	bool ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject) override;

	class SWGCurrencyErrorDetails : public ErrorDetails
	{
	public:
		virtual ~SWGCurrencyErrorDetails() {}
		bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	};
	const SWGCurrencyErrorDetails& GetError() const { check(_Error); return *_Error.Get(); }
    
    //TODO: error vars here

private:
	TUniquePtr<SWGCurrencyErrorDetails> _Error;
};


}
