/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "Modules/ModuleInterface.h"
#include "Modules/ModuleManager.h"
#include "Logging/LogMacros.h"

#include "SWGAPI.h"

DECLARE_LOG_CATEGORY_EXTERN(LogSWG, Log, All);

class SWG_API SWGModule : public IModuleInterface
{
public:
	void StartupModule() override;
	void ShutdownModule() override;

    /**
    * Singleton-like access to this module's interface.  This is just for convenience!
    * Beware of calling this during the shutdown phase, though.  Your module might have been unloaded already.
    *
    * @return Returns singleton instance, loading the module on demand if needed
    */
    static inline SWGModule& Get()
    {
        return FModuleManager::LoadModuleChecked<SWGModule>("SWG");
    }

    TSharedPtr<SWG::SWGAPI> CreateClientAPI() const;
};
