/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "SWGModel.h"

#include "FDateTime.h"

#include "SWGObject.h"

namespace Swagger 
{


/*
 * SWGOrder.h
 *
 * An order for a pets from the pet store
 */
class SWG_API SWGOrderRequest: public Request
{
public:
    virtual ~SWGOrder() {}
    bool IsValid() const override;
	TSharedPtr<FJsonObject> ToJson() const override;
    
    int64 id = 0L;
    int64 pet_id = 0L;
    int32 quantity = 0;
    FDateTime* ship_date = NULL;
    FString status = new FString("");
    bool complete = false;
};

class SWG_API SWGOrderResponse: public Response
{
public:
    virtual ~SWGOrder() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	bool ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject) override;

	class SWGOrderErrorDetails : public ErrorDetails
	{
	public:
		virtual ~SWGOrderErrorDetails() {}
		bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	};
	const SWGOrderErrorDetails& GetError() const { check(_Error); return *_Error.Get(); }
    
    //TODO: error vars here
    int64 id;
    int64 pet_id;
    int32 quantity;
    FDateTime* ship_date;
    FString status;
    bool complete;

private:
	TUniquePtr<SWGOrderErrorDetails> _Error;
};


}
