/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGOrder.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"

namespace Swagger 
{



	bool SWGOrderRequest::IsValid() const
	{
        //TODO: test which parameters need to be set for valid request
		return true;
	}

    TSharedPtr<FJsonObject> SWGOrderRequest::ToJson() const
	{
		auto JsonObject = MakeShared<FJsonObject>();

        JsonObject->SetNumberField("id", id);
        JsonObject->SetNumberField("pet_id", pet_id);
        JsonObject->SetNumberField("quantity", quantity);
        JsonObject->SetNumberField("ship_date", ship_date);
        JsonObject->SetNumberField("status", status);
        JsonObject->SetNumberField("complete", complete);

		return JsonObject;
	}

	bool SWGOrderResponse::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
	{
		bool ParseSuccess = true;

        ParseSuccess &= JsonObject->TryGetNumberField("id", id);
        ParseSuccess &= JsonObject->TryGetNumberField("pet_id", pet_id);
        ParseSuccess &= JsonObject->TryGetNumberField("quantity", quantity);
        ParseSuccess &= JsonObject->TryGetNumberField("ship_date", ship_date);
        ParseSuccess &= JsonObject->TryGetNumberField("status", status);
        ParseSuccess &= JsonObject->TryGetNumberField("complete", complete);

		return ParseSuccess;
	}

	bool SWGOrderResponse::ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject)
	{
		_Error = MakeUnique<SWGOrderErrorDetails>();
		return _Error->FromJson(JsonObject);
	}

	bool SWGOrderResponse::SWGOrderErrorDetails::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
	{
		//TODO :!
		return true;
	}
}


}
