/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "SWGModel.h"

#include "SWGCategory.h"
#include "SWGTag.h"

#include "SWGObject.h"

namespace Swagger 
{


/*
 * SWGPet.h
 *
 * A pet for sale in the pet store
 */
class SWG_API SWGPetRequest: public Request
{
public:
    virtual ~SWGPet() {}
    bool IsValid() const override;
	TSharedPtr<FJsonObject> ToJson() const override;
    
    int64 id = 0L;
    SWGCategory* category = new SWGCategory();
    FString name = new FString("");
    TArray<FString>* photo_urls = new TArray<FString>();
    TArray<SWGTag*>* tags = new TArray<SWGTag*>();
    FString status = new FString("");
};

class SWG_API SWGPetResponse: public Response
{
public:
    virtual ~SWGPet() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	bool ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject) override;

	class SWGPetErrorDetails : public ErrorDetails
	{
	public:
		virtual ~SWGPetErrorDetails() {}
		bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	};
	const SWGPetErrorDetails& GetError() const { check(_Error); return *_Error.Get(); }
    
    //TODO: error vars here
    int64 id;
    SWGCategory* category;
    FString name;
    TArray<FString>* photo_urls;
    TArray<SWGTag*>* tags;
    FString status;

private:
	TUniquePtr<SWGPetErrorDetails> _Error;
};


}
