/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "SWGModel.h"


#include "SWGObject.h"

namespace Swagger 
{


/*
 * SWGTag.h
 *
 * A tag for a pet
 */
class SWG_API SWGTagRequest: public Request
{
public:
    virtual ~SWGTag() {}
    bool IsValid() const override;
	TSharedPtr<FJsonObject> ToJson() const override;
    
    int64 id = 0L;
    FString name = new FString("");
};

class SWG_API SWGTagResponse: public Response
{
public:
    virtual ~SWGTag() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	bool ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject) override;

	class SWGTagErrorDetails : public ErrorDetails
	{
	public:
		virtual ~SWGTagErrorDetails() {}
		bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	};
	const SWGTagErrorDetails& GetError() const { check(_Error); return *_Error.Get(); }
    
    //TODO: error vars here
    int64 id;
    FString name;

private:
	TUniquePtr<SWGTagErrorDetails> _Error;
};


}
