/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "SWGModel.h"


#include "SWGObject.h"

namespace Swagger 
{


/*
 * SWGUser.h
 *
 * A User who is purchasing from the pet store
 */
class SWG_API SWGUserRequest: public Request
{
public:
    virtual ~SWGUser() {}
    bool IsValid() const override;
	TSharedPtr<FJsonObject> ToJson() const override;
    
    int64 id = 0L;
    FString username = new FString("");
    FString first_name = new FString("");
    FString last_name = new FString("");
    FString email = new FString("");
    FString password = new FString("");
    FString phone = new FString("");
    int32 user_status = 0;
};

class SWG_API SWGUserResponse: public Response
{
public:
    virtual ~SWGUser() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	bool ErrorFromJson(const TSharedPtr<FJsonObject>& JsonObject) override;

	class SWGUserErrorDetails : public ErrorDetails
	{
	public:
		virtual ~SWGUserErrorDetails() {}
		bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) override;
	};
	const SWGUserErrorDetails& GetError() const { check(_Error); return *_Error.Get(); }
    
    //TODO: error vars here
    int64 id;
    FString username;
    FString first_name;
    FString last_name;
    FString email;
    FString password;
    FString phone;
    int32 user_status;

private:
	TUniquePtr<SWGUserErrorDetails> _Error;
};


}
